// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package calendar.model;

import java.util.Date;

privileged aspect OpenTime_Roo_JavaBean {
    
    public Date OpenTime.getOpenDay() {
        return this.openDay;
    }
    
    public void OpenTime.setOpenDay(Date openDay) {
        this.openDay = openDay;
    }
    
}
