// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package calendar.model;

import calendar.model.DayOfWeek;

privileged aspect OpenTimeRecurring_Roo_JavaBean {
    
    public DayOfWeek OpenTimeRecurring.getOpenDay() {
        return this.openDay;
    }
    
    public void OpenTimeRecurring.setOpenDay(DayOfWeek openDay) {
        this.openDay = openDay;
    }
    
}
