// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package calendar.model;

import java.lang.String;

privileged aspect SystemAuthority_Roo_JavaBean {
    
    public String SystemAuthority.getAuthority() {
        return this.authority;
    }
    
    public void SystemAuthority.setAuthority(String authority) {
        this.authority = authority;
    }
    
}
